[project]
name = "repl-nix-ollama-python-sandbox"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.27.2",
    "ollama>=0.4.2",
    "tqdm>=4.67.1",
]
